### ISSUE TITLE
Using with HDK2 causes problems

### ISSUE THREAD

**Issue by meruune** [simlrh/OSVR-fusion#5]
When I use "/me/head" with fused device (kinect head with osvr rot) it always works on tracker view and with sample scene, but never in steamvr. If I'm launching it, it works but there's problem: screen has only one color. I used both fusion and kinect plugins, never worked. Without using fusion and only rotation from hmd steamvr works perfectly BUT not tracks.
Pls-help!

**Comment by simlrh** [comment]
> it always works on tracker view and with sample scene, but never in steamvr

Then it's a steamvr or osvr-steamvr issue. There's no way tracking code would affect rendering. 

TBH I suspect your positional tracking isn't centered putting you behind a solid wall or something.
